# ClusterSql.yml
- hosts: node04
  gather_facts: true
  become: true

  tasks:

################################################
# Configuration MariaDB Cluster 
###############################################

  - name: Stop Mariadb
    service: name=mariadb state=stopped 

  - name: Mysql - Transfert conf Node04
    template: src=/home/cp219538/MysqlConf/mysql-node04-my.cnf dest=/etc/my.cnf owner=root mode=0644

  - name: Mysql - Supprime les fichiers
    raw: rm -rf /var/lib/mysql/*

  - name: Relance Mariadb
    service: name=mariadb state=started 

########################################
# Recreation du Root Password Mysql
########################################

  - name: SUppression fichier précedent
    raw: rm -f /root/.my.cnf

  - name: Transfert Credentiels Mysql
    template: src=/home/cp219538/MysqlConf/mysql_root.my.cnf dest=/root/.my.cnf owner=root mode=0600

  - name: Suppression base TEST
    mysql_db: name=test state=absent


